name: learn-github-actions
on: [push]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # @v3 specifies the version of the action.
      - name: setup python
        uses: actions/setup-python@v3 #@v3 is current here too. https://github.com/marketplace/actions/setup-python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run unnittest checks
        run: python -m test_string_thing_unittest.py
      - name: Run pytest checks
        run: pytest test_string_thing_pytest.py
