name: pull-request
on:
  pull_request:
    types: [opened, reopened]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3 # @v3 specifies the version of the action.
      - name: setup python
        uses: actions/setup-python@v3 #@v3 is current here too. https://github.com/marketplace/actions/setup-python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Flake8 install
        run: pip install flake8
      - name: Flake8 Run
        run: flake8 --max-line-length=127 --ignore=E302 .
      - name: Run pytest checks
        run: pytest test_string_thing_pytest.py
        